### ISSUE TITLE
Wrong domain name for header

### ISSUE THREAD

**Issue by juliencampion** [LeBarbu/vim-epitech#9]
Vim's Epitech header says:
'Login   campio_j@epitech.eu'
While Emacs's Epitech header says:
'Login   campio_j@epitech.net'.

I believe the right domain name is epitech.net.

**Comment by casimir** [comment]
Both works but let's respect the past.

**Comment by deadbaed** [comment]
that is weird, because the email addresses dont work in `.net` in 2018...

plus i think the emacs header changed back to the `.eu` domain, i.e this file <https://github.com/flupine/Piscine/blob/master/DAY03/my_print_comb2.c> made on **october 9, 2017**

should we revert the change? a simple git revert on the commit you made @casimir should do the trick.

that would be great, thank you!
